# Script for populating the database. You can run it as:
#
#     mix run priv/repo/seeds.exs
#
# Inside the script, you can read and write to any of your
# repositories directly:
#
#     VtmAuth.Repo.insert(%VtmAuth.SomeSchema{})
#
# We recommend using the bang functions (`insert`, `update!`
# and so on) as they will fail if something goes wrong.

{:ok, %{id: phisical_attribute_id}} = Vtm.Repo.insert(%Vtm.Characters.AttributeType{name: "Attribute", section: "Physical"})
{:ok, %{id: social_attribute_id}} = Vtm.Repo.insert(%Vtm.Characters.AttributeType{name: "Attribute", section: "Social"})
{:ok, %{id: mental_attribute_id}} = Vtm.Repo.insert(%Vtm.Characters.AttributeType{name: "Attribute", section: "Mental"})
{:ok, %{id: phisical_ability_id}} = Vtm.Repo.insert(%Vtm.Characters.AttributeType{name: "Ability", section: "Physical"})
{:ok, %{id: social_ability_id}} = Vtm.Repo.insert(%Vtm.Characters.AttributeType{name: "Ability", section: "Social"})
{:ok, %{id: mental_ability_id}} = Vtm.Repo.insert(%Vtm.Characters.AttributeType{name: "Ability", section: "Mental"})
{:ok, %{id: advantage_id}} = Vtm.Repo.insert(%Vtm.Characters.AttributeType{name: "Advantage", section: ""})
{:ok, %{id: discipline_id}} = Vtm.Repo.insert(%Vtm.Characters.AttributeType{name: "Discipline", section: ""})

Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: phisical_attribute_id, name: "Strength", description: "Strength"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: phisical_attribute_id, name: "Dexterity", description: "Dexterity"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: phisical_attribute_id, name: "Stamina", description: "Stamina"})

Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: social_attribute_id, name: "Charisma", description: "Charisma"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: social_attribute_id, name: "Manipulation", description: "Manipulation"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: social_attribute_id, name: "Composure", description: "Composure"})

Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: mental_attribute_id, name: "Intelligence", description: "Intelligence"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: mental_attribute_id, name: "Wits", description: "Wits"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: mental_attribute_id, name: "Resolve", description: "Resolve"})

Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: phisical_ability_id, name: "Athletics", description: "Athletics"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: phisical_ability_id, name: "Brawl", description: "Brawl"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: phisical_ability_id, name: "Craft", description: "Craft"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: phisical_ability_id, name: "Drive", description: "Drive"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: phisical_ability_id, name: "Firearms", description: "Firearms"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: phisical_ability_id, name: "Larceny", description: "Larceny"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: phisical_ability_id, name: "Melee", description: "Melee"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: phisical_ability_id, name: "Stealth", description: "Stealth"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: phisical_ability_id, name: "Survival", description: "Survival"})

Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: social_ability_id, name: "Animal Ken", description: "Animal Ken"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: social_ability_id, name: "Etiquette", description: "Etiquette"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: social_ability_id, name: "Insight", description: "Insight"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: social_ability_id, name: "Intimidation", description: "Intimidation"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: social_ability_id, name: "Leadership", description: "Leadership"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: social_ability_id, name: "Performance", description: "Performance"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: social_ability_id, name: "Persuasion", description: "Persuasion"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: social_ability_id, name: "Streetwise", description: "Streetwise"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: social_ability_id, name: "Subterfuge", description: "Subterfuge"})

Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: mental_ability_id, name: "Academics", description: "Academics"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: mental_ability_id, name: "Awarness", description: "Awarness"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: mental_ability_id, name: "Finance", description: "Finance"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: mental_ability_id, name: "Investigation", description: "Investigation"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: mental_ability_id, name: "Medicins", description: "Medicins"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: mental_ability_id, name: "Occult", description: "Occult"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: mental_ability_id, name: "Politics", description: "Politics"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: mental_ability_id, name: "Science", description: "Science"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: mental_ability_id, name: "Technology", description: "Technology"})

{:ok, animalism} = Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: discipline_id, name: "Animalism", description: "Animalism"})
{:ok, auspex} = Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: discipline_id, name: "Auspex", description: "Auspex"})
{:ok, blood_sorcery} = Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: discipline_id, name: "Blood Sorcery", description: "Blood Sorcery"})
{:ok, celerity} = Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: discipline_id, name: "Celerity", description: "Celerity"})
{:ok, dominate} = Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: discipline_id, name: "Dominate", description: "Dominate"})
{:ok, fortitude} = Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: discipline_id, name: "Fortitude", description: "Fortitude"})
{:ok, obfuscate} = Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: discipline_id, name: "Obfuscate", description: "Obfuscate"})
{:ok, oblivion} = Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: discipline_id, name: "Oblivion", description: "Oblivion"})
{:ok, potence} = Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: discipline_id, name: "Potence", description: "Potence"})
{:ok, presence} = Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: discipline_id, name: "Presence", description: "Presence"})
{:ok, protean} = Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: discipline_id, name: "Protean", description: "Protean"})
{:ok, alchemy} = Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: discipline_id, name: "Thin-Blood Alchemy", description: "Thin-Blood Alchemy"})

Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: advantage_id, name: "Allies", description: "Allies"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: advantage_id, name: "Contacts", description: "Contacts"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: advantage_id, name: "Fame", description: "Fame"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: advantage_id, name: "Haven", description: "Haven"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: advantage_id, name: "Herd", description: "Herd"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: advantage_id, name: "Influence", description: "Influence"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: advantage_id, name: "Loresheet", description: "Loresheet"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: advantage_id, name: "Mask", description: "Mask"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: advantage_id, name: "Mawla", description: "Mawla"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: advantage_id, name: "Resources", description: "Resources"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: advantage_id, name: "Retainers", description: "Retainers"})
Vtm.Repo.insert(%Vtm.Characters.Attribute{attribute_type_id: advantage_id, name: "Status", description: "Status"})

Vtm.Repo.insert(%Vtm.Characters.Clan{name: "Humans"})
Vtm.Repo.insert(%Vtm.Characters.Clan{name: "ThinBlood", attributes: [alchemy]})
Vtm.Repo.insert(%Vtm.Characters.Clan{name: "Caitiff", attributes: [auspex, celerity, fortitude, obfuscate, potence, presence]})
Vtm.Repo.insert(%Vtm.Characters.Clan{name: "BanuHaquim", attributes: [blood_sorcery, celerity, obfuscate]})
Vtm.Repo.insert(%Vtm.Characters.Clan{name: "Brujah", attributes: [celerity, potence, presence]})
Vtm.Repo.insert(%Vtm.Characters.Clan{name: "Gangrel", attributes: [animalism, fortitude, protean]})
Vtm.Repo.insert(%Vtm.Characters.Clan{name: "Hecata", attributes: [oblivion, dominate, auspex, potence]})
Vtm.Repo.insert(%Vtm.Characters.Clan{name: "Malkavian", attributes: [auspex, dominate, obfuscate]})
Vtm.Repo.insert(%Vtm.Characters.Clan{name: "Ministry", attributes: [obfuscate, presence, protean]})
Vtm.Repo.insert(%Vtm.Characters.Clan{name: "Nosferatu", attributes: [animalism, obfuscate, potence]})
Vtm.Repo.insert(%Vtm.Characters.Clan{name: "Lasombra", attributes: [dominate, oblivion, potence]})
Vtm.Repo.insert(%Vtm.Characters.Clan{name: "Ravnos", attributes: [animalism, fortitude, presence]})
Vtm.Repo.insert(%Vtm.Characters.Clan{name: "Salubri", attributes: [auspex, dominate, fortitude]})
Vtm.Repo.insert(%Vtm.Characters.Clan{name: "Toreador", attributes: [auspex, celerity, presence]})
Vtm.Repo.insert(%Vtm.Characters.Clan{name: "Tremere", attributes: [auspex, blood_sorcery, dominate]})
Vtm.Repo.insert(%Vtm.Characters.Clan{name: "Tzimisce", attributes: [auspex, dominate, protean]})
Vtm.Repo.insert(%Vtm.Characters.Clan{name: "Ventrue", attributes: [dominate, fortitude, presence]})

# Vtm.Seeds.Helpers.insert_clan_discipline_association(thin_blood, [alchemy])
# Vtm.Seeds.Helpers.insert_clan_discipline_association(caitiff, [auspex, celerity, fortitude, obfuscate, potence, presence])
# Vtm.Seeds.Helpers.insert_clan_discipline_association(banu_haquim, [blood_sorcery, celerity, obfuscate])
# Vtm.Seeds.Helpers.insert_clan_discipline_association(bruja, [celerity, potence, presence])
# Vtm.Seeds.Helpers.insert_clan_discipline_association(gangrel, [animalism, fortitude, protean])
# Vtm.Seeds.Helpers.insert_clan_discipline_association(hecata, [oblivion, dominate, auspex, potence])
# Vtm.Seeds.Helpers.insert_clan_discipline_association(malkavian, [auspex, dominate, obfuscate])
# Vtm.Seeds.Helpers.insert_clan_discipline_association(ministry, [obfuscate, presence, protean])
# Vtm.Seeds.Helpers.insert_clan_discipline_association(nosferatu, [animalism, obfuscate, potence])
# Vtm.Seeds.Helpers.insert_clan_discipline_association(lasombra, [dominate, oblivion, potence])
# Vtm.Seeds.Helpers.insert_clan_discipline_association(ravnos, [animalism, fortitude, presence])
# Vtm.Seeds.Helpers.insert_clan_discipline_association(salubri, [auspex, dominate, fortitude])
# Vtm.Seeds.Helpers.insert_clan_discipline_association(toreador, [auspex, celerity, presence])
# Vtm.Seeds.Helpers.insert_clan_discipline_association(tremere, [auspex, blood_sorcery, dominate])
# Vtm.Seeds.Helpers.insert_clan_discipline_association(tzimisce, [auspex, dominate, protean])
# Vtm.Seeds.Helpers.insert_clan_discipline_association(ventrue, [dominate, fortitude, presence])

Vtm.Repo.insert(%Vtm.Characters.PredatorType{name: "Alleycat", description: "Alleycat"})
Vtm.Repo.insert(%Vtm.Characters.PredatorType{name: "Bagger", description: "Bagger"})
Vtm.Repo.insert(%Vtm.Characters.PredatorType{name: "BloodLeech", description: "BloodLeech"})
Vtm.Repo.insert(%Vtm.Characters.PredatorType{name: "Cleaver", description: "Cleaver"})
Vtm.Repo.insert(%Vtm.Characters.PredatorType{name: "Consensualist", description: "Consensualist"})
Vtm.Repo.insert(%Vtm.Characters.PredatorType{name: "Farmer", description: "Farmer"})
Vtm.Repo.insert(%Vtm.Characters.PredatorType{name: "Osiris", description: "Osiris"})
Vtm.Repo.insert(%Vtm.Characters.PredatorType{name: "Sandman", description: "Sandman"})
Vtm.Repo.insert(%Vtm.Characters.PredatorType{name: "SceneQueen", description: "SceneQueen"})
Vtm.Repo.insert(%Vtm.Characters.PredatorType{name: "Siren", description: "Siren"})

{:ok, %{id: palermo_id}} = Vtm.Repo.insert(%Vtm.Chats.ChatMap{name: "Palermo", is_chat: false})
Vtm.Repo.insert(%Vtm.Chats.ChatMap{name: "Recoleta", is_chat: false})
Vtm.Repo.insert(%Vtm.Chats.ChatMap{name: "Puerto Madero", is_chat: false})
Vtm.Repo.insert(%Vtm.Chats.ChatMap{name: "Retiro", is_chat: false})
Vtm.Repo.insert(%Vtm.Chats.ChatMap{name: "Barracas", is_chat: false})

Vtm.Repo.insert(%Vtm.Chats.ChatMap{name: "Plaza Garibaldi", is_chat: true, chat_map_id: palermo_id})
