# Script for populating the database. You can run it as:
#
#     mix run priv/repo/seeds.exs
#
# Inside the script, you can read and write to any of your
# repositories directly:
#
#     VtmAuth.Repo.insert!(%VtmAuth.SomeSchema{})
#
# We recommend using the bang functions (`insert!`, `update!`
# and so on) as they will fail if something goes wrong.
Vtm.Repo.insert!(%Vtm.Characters.Clan{name: "Humans"})
Vtm.Repo.insert!(%Vtm.Characters.Clan{name: "Thin Blood"})
Vtm.Repo.insert!(%Vtm.Characters.Clan{name: "Caitiff"})
Vtm.Repo.insert!(%Vtm.Characters.Clan{name: "Banu Haquim"})
Vtm.Repo.insert!(%Vtm.Characters.Clan{name: "Brujah"})
Vtm.Repo.insert!(%Vtm.Characters.Clan{name: "Gangrel"})
Vtm.Repo.insert!(%Vtm.Characters.Clan{name: "Hecata"})
Vtm.Repo.insert!(%Vtm.Characters.Clan{name: "Malkavian"})
Vtm.Repo.insert!(%Vtm.Characters.Clan{name: "Ministry"})
Vtm.Repo.insert!(%Vtm.Characters.Clan{name: "Nosferatu"})
Vtm.Repo.insert!(%Vtm.Characters.Clan{name: "Lasombra"})
Vtm.Repo.insert!(%Vtm.Characters.Clan{name: "Ravnos"})
Vtm.Repo.insert!(%Vtm.Characters.Clan{name: "Salubri"})
Vtm.Repo.insert!(%Vtm.Characters.Clan{name: "Toreador"})
Vtm.Repo.insert!(%Vtm.Characters.Clan{name: "Tremere"})
Vtm.Repo.insert!(%Vtm.Characters.Clan{name: "Tzimisce"})
Vtm.Repo.insert!(%Vtm.Characters.Clan{name: "Ventrue"})

%{id: phisical_attribute_id} = Vtm.Repo.insert!(%Vtm.Characters.AttributeType{name: "Attribute", section: "Physical"})
%{id: social_attribute_id} = Vtm.Repo.insert!(%Vtm.Characters.AttributeType{name: "Attribute", section: "Social"})
%{id: mental_attribute_id} = Vtm.Repo.insert!(%Vtm.Characters.AttributeType{name: "Attribute", section: "Mental"})
%{id: phisical_ability_id} = Vtm.Repo.insert!(%Vtm.Characters.AttributeType{name: "Ability", section: "Physical"})
%{id: social_ability_id} = Vtm.Repo.insert!(%Vtm.Characters.AttributeType{name: "Ability", section: "Social"})
%{id: mental_ability_id} = Vtm.Repo.insert!(%Vtm.Characters.AttributeType{name: "Ability", section: "Mental"})
%{id: advantage_id} = Vtm.Repo.insert!(%Vtm.Characters.AttributeType{name: "Advantage", section: ""})
%{id: discipline_id} = Vtm.Repo.insert!(%Vtm.Characters.AttributeType{name: "Discipline", section: ""})

Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: phisical_attribute_id, name: "Strength", description: "Strength"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: phisical_attribute_id, name: "Dexterity", description: "Dexterity"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: phisical_attribute_id, name: "Stamina", description: "Stamina"})

Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: social_attribute_id, name: "Charisma", description: "Charisma"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: social_attribute_id, name: "Manipulation", description: "Manipulation"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: social_attribute_id, name: "Composure", description: "Composure"})

Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: mental_attribute_id, name: "Intelligence", description: "Intelligence"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: mental_attribute_id, name: "Wits", description: "Wits"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: mental_attribute_id, name: "Resolve", description: "Resolve"})

Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: phisical_ability_id, name: "Athletics", description: "Athletics"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: phisical_ability_id, name: "Brawl", description: "Brawl"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: phisical_ability_id, name: "Craft", description: "Craft"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: phisical_ability_id, name: "Drive", description: "Drive"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: phisical_ability_id, name: "Firearms", description: "Firearms"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: phisical_ability_id, name: "Larceny", description: "Larceny"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: phisical_ability_id, name: "Melee", description: "Melee"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: phisical_ability_id, name: "Stealth", description: "Stealth"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: phisical_ability_id, name: "Survival", description: "Survival"})

Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: social_ability_id, name: "Animal Ken", description: "Animal Ken"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: social_ability_id, name: "Etiquette", description: "Etiquette"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: social_ability_id, name: "Insight", description: "Insight"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: social_ability_id, name: "Intimidation", description: "Intimidation"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: social_ability_id, name: "Leadership", description: "Leadership"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: social_ability_id, name: "Performance", description: "Performance"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: social_ability_id, name: "Persuasion", description: "Persuasion"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: social_ability_id, name: "Streetwise", description: "Streetwise"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: social_ability_id, name: "Subterfuge", description: "Subterfuge"})

Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: mental_ability_id, name: "Academics", description: "Academics"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: mental_ability_id, name: "Awarness", description: "Awarness"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: mental_ability_id, name: "Finance", description: "Finance"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: mental_ability_id, name: "Investigation", description: "Investigation"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: mental_ability_id, name: "Medicins", description: "Medicins"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: mental_ability_id, name: "Occult", description: "Occult"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: mental_ability_id, name: "Politics", description: "Politics"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: mental_ability_id, name: "Science", description: "Science"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: mental_ability_id, name: "Technology", description: "Technology"})

Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: discipline_id, name: "Animalism", description: "Animalism"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: discipline_id, name: "Auspex", description: "Auspex"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: discipline_id, name: "Blood Sorcery", description: "Blood Sorcery"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: discipline_id, name: "Celerity", description: "Celerity"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: discipline_id, name: "Dominate", description: "Dominate"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: discipline_id, name: "Fortitude", description: "Fortitude"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: discipline_id, name: "Obfuscate", description: "Obfuscate"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: discipline_id, name: "Oblivion", description: "Oblivion"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: discipline_id, name: "Potence", description: "Potence"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: discipline_id, name: "Presence", description: "Presence"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: discipline_id, name: "Protean", description: "Protean"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: discipline_id, name: "Thin-Blood Alchemy", description: "Thin-Blood Alchemy"})

Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: advantage_id, name: "Allies", description: "Allies"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: advantage_id, name: "Contacts", description: "Contacts"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: advantage_id, name: "Fame", description: "Fame"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: advantage_id, name: "Haven", description: "Haven"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: advantage_id, name: "Herd", description: "Herd"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: advantage_id, name: "Influence", description: "Influence"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: advantage_id, name: "Loresheet", description: "Loresheet"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: advantage_id, name: "Mask", description: "Mask"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: advantage_id, name: "Mawla", description: "Mawla"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: advantage_id, name: "Resources", description: "Resources"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: advantage_id, name: "Retainers", description: "Retainers"})
Vtm.Repo.insert!(%Vtm.Characters.Attribute{attribute_type_id: advantage_id, name: "Status", description: "Status"})

Vtm.Repo.insert!(%Vtm.Characters.PredatorType{name: "Alleycat", description: "Alleycat"})
Vtm.Repo.insert!(%Vtm.Characters.PredatorType{name: "Bagger", description: "Bagger"})
Vtm.Repo.insert!(%Vtm.Characters.PredatorType{name: "BloodLeech", description: "BloodLeech"})
Vtm.Repo.insert!(%Vtm.Characters.PredatorType{name: "Cleaver", description: "Cleaver"})
Vtm.Repo.insert!(%Vtm.Characters.PredatorType{name: "Consensualist", description: "Consensualist"})
Vtm.Repo.insert!(%Vtm.Characters.PredatorType{name: "Farmer", description: "Farmer"})
Vtm.Repo.insert!(%Vtm.Characters.PredatorType{name: "Osiris", description: "Osiris"})
Vtm.Repo.insert!(%Vtm.Characters.PredatorType{name: "Sandman", description: "Sandman"})
Vtm.Repo.insert!(%Vtm.Characters.PredatorType{name: "SceneQueen", description: "SceneQueen"})
Vtm.Repo.insert!(%Vtm.Characters.PredatorType{name: "Siren", description: "Siren"})
