name: Build Image for ACR
on:
  push:
    branches: [main, acr-test]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ACR build
        id: acr
        uses: azure/acr-build@v1
        with:
          service_principal: d19aa1b0-8894-4d0a-806f-117bd556e2ae
          service_principal_password: ${{ secrets.service_principal_password }}
          tenant: b4a3e2d3-2d99-4b3e-a15e-5a85d655c544
          registry: vtmbaires
          repository: vtmbaires
          image: vtmbaires
          git_access_token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: DockerfileGithubAction
          branch: main
          build_args: |
            [
              {"db_url": "${{ secrets.POSTGRES_CONN_STRING }}"},
              {"secret_key": "${{ secrets.SECRET_KEY_STRING }}"},
              {"mail_smtps_server": "smtps.aruba.it"},
              {"mail_port": 465},
              {"mail_user": "postmaster@vtmbaires.eu"},
              {"mail_pass": "${{ secrets.MAIL_PWD }}"}
            ]

      # - name: Update Docker Compose
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.TEST_HOST }}
      #     username: ${{ secrets.TEST_USERNAME }}
      #     password: ${{ secrets.TEST_PASSWORD }}
      #     port: ${{ secrets.TEST_PORT }}
      #     script: /usr/bin/deploy.sh
